name: Build Thesis

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Thesis PDF
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    env:
      TZ: 'America/Toronto'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build PDF
        run: |
          latexmk -lualatex thesis.tex

      - name: Set timestamp
        id: timestamp
        run: |
          echo "READABLE=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update Corrections Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: corrections
          name: Thesis Corrections (Latest)
          files: thesis.pdf
          body: |
            This release contains the latest corrections, made after the official UWSpace submission.
            It is intended for personal use and reference, and is not an official version of the thesis.
            For the official version, please refer to the UWSpace submission.

            Last updated on: ${{ steps.timestamp.outputs.READABLE }}
            From commit: ${{ github.sha }}
          draft: false
          prerelease: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}